name: 'Create/Update Release'
run-name: 'Push to release branch'

on:
  push:
    branches:
    - release/*

permissions:
  id-token: write
  contents: write
  pull-requests: read

jobs:
  CreateNewRelease:
    name: 'Create New Release'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 'Get next release version'
      id: get-release-tag
      shell: pwsh
      run: |
        git fetch --tags
        $currentBranch = git rev-parse --abbrev-ref HEAD
        $releaseBranchVersion = ($currentBranch -split '/' | Select-Object -Last 1) -replace "v",""
        $tags = git tag

        # Check for a match
        $matches = ($tags -match "^[vV]?$releaseBranchVersion([.][0-9]+)?$") -replace "v",""
        $matchFound = $false

        # Output result
        if ($matchFound) {
          Write-Output "A tag matching the release version $releaseBranchVersion was found."
          # Get most recent tag for release
          $latestTag = $matches | Sort-Object -Descending | Select-Object -First 1
          $major,$minor,$patch = $latestTag.Split('.')
          [int]$patch+=1
          Write-Output "A new release will be created with a bump to the patch. New version: $major.$minor.$patch"
          "newReleaseVersion=$major.$minor.$patch" >> $env:GITHUB_OUTPUT
        }
        else {
          Write-Output "No matching tag found for $releaseBranchVersion. Creating a new release for release branch"

          "newReleaseVersion=$major.$minor.$patch" >> $env:GITHUB_OUTPUT
        }

    - name: Get tags of elements
      id: get-associated-tags
      shell: pwsh
      run: |
        $tagBody = "### Contents: `r`n"
        $elements = Get-Content changed-files-config.json | ConvertFrom-Json | Select-Object -ExpandProperty elements
        foreach ($element in $elements) {
          Write-Debug "Element: $($element.name)"
          $newestCommit = ""
          foreach ($path in $element.path) {
            Write-Debug "  Path: $path"
            $commitHash = git log --before="$(git log -n 1 --pretty=format:'%cI')" -n 1 --pretty=format:"%H" -- $path
            $childCommit = git log --all --pretty=format:'%H %P' | Select-String " $commitHash" | ForEach-Object { $_.ToString().Split(' ')[0] }
            if ($newestCommit) {
              if (git merge-base --is-ancestor $newestCommit $childCommit) {
                $newestCommit = $childCommit
              }
            }
            else {
              $newestCommit = $childCommit
            }
          }
          # Add code to get tag from commit, match specific element
          $tag = git tag --points-at $newestCommit | Select-String "$($element.name)-v*" 
          Write-Debug "Tag: $tag"
          $tagBody += " Element: $($element.name) `r`n"
          $tagBody += "   Latest Tag: $tag `r`n"
          $tagBody += "   Latest Commit: $newestCommit `r`n`r`n"
        }
        write-output "$tagBody"
        "tagBody=$tagBody" >> $env:GITHUB_OUTPUT
        

        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 'v${{ steps.get-release-tag.outputs.newReleaseVersion }}'
        release_name: 'v${{ steps.get-release-tag.outputs.newReleaseVersion }}'
        draft: false
        prerelease: false
        body: ${{ steps.get-associated-tags.outputs.tagBody }}

    - name: Output to Job Summary
      id: output-element
      shell: pwsh
      run: |
        Write-Host "New Release/Tag: v${{ steps.get-release-tag.outputs.newReleaseVersion }}"
        "# :rocket: :bookmark: New Release/Tag: v${{ steps.get-release-tag.outputs.newReleaseVersion }} `r`n" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
        "## Branch: ${{ github.ref_name }} `r`n" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
        "## Release Notes: `r`n ${{ steps.get-associated-tags.outputs.tagBody }}" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append